name: Sync to Hugging Face

on:
  push:
    branches: [main] # hoặc branch bạn muốn sync
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # cần full history
          lfs: true # rất quan trọng nếu có file lớn

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://megaphuongdo:${HF_TOKEN}@huggingface.co/spaces/megaphuongdo/b3hauc3-images main --force
          # Ví dụ cho Space:
          # git remote add hf https://huggingface.co/spaces/tênuser/tênspace

          # Ví dụ cho Model:
          # git remote add hf https://huggingface.co/tênuser/tênmodel

          # Ví dụ cho Dataset:
          # git remote add hf https://huggingface.co/datasets/tênuser/têndataset

          git push hf main --force
          # hoặc nếu branch khác: git push hf tênbranch:tênbranch
